<?php
namespace app\home\controller;
use think\Controller;
class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $navList = $this->getNavList();
        $this->assign('navList',$navList);
    }

    public function index(){

        return  $this->fetch();
    }
    
    public function index2()
    {

        return  $this->fetch();

    }

    public function getNavList(){

      return   $navList = db('nav')->where('status=1')->order('order_num desc,id asc')->select();
    }
}
